#!/bin/bash

## Description: run php-cs-fixer on all php files staged in git and re-add them after

CHANGED_FILES=$(git diff --name-only --cached --diff-filter=ACMR -- '*.php')
if [[ -n "$CHANGED_FILES" ]]; then
    for FILE in $CHANGED_FILES; do
        ddev fix "$FILE"
        git add "$FILE"
    done
fi