#!/bin/bash

# run php cs fixer on given files

HAS_COMPOSER_ROOT=$(yq '. | has("composer_root")' .ddev/config.yaml)
if [ $HAS_COMPOSER_ROOT == "true" ]
then
    COMPOSER_ROOT=(`yq e '.composer_root' .ddev/config.yaml`)
else
    COMPOSER_ROOT='.'
fi
if [ -f "$COMPOSER_ROOT/vendor/bin/php-cs-fixer" ]
then
    if [ -f "$COMPOSER_ROOT/.php-cs-fixer.dist.php" ]
    then
        if [[ -z  $@  ]]
        then 
            read -p "no files given, this will fix all php files in the project, Are you sure? " -n 1 -r
            echo    # (optional) move to a new line
            if [[ $REPLY =~ ^[Yy]$ ]]
            then
                php-cs-fixer --config="$COMPOSER_ROOT/.php-cs-fixer.dist.php" fix $@
            fi
        else
            php-cs-fixer --config="$COMPOSER_ROOT/.php-cs-fixer.dist.php" fix $@
        fi
    else
        echo "no php cs fixer found at $COMPOSER_ROOT/.php-cs-fixer.dist.php"
    fi
else
    echo "no php cs fixer installed"
fi
